[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
abc = "7mMu435prH2sgPhnT2UuYTCCMfQyxdA8XpwLX7sEx6L7"
puppet = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
zero_cpi = "ErjUjtqKE5AGWUsjseSJCVLtddM6rhaMbDqmhzraF9h6"
zero_copy = "3M1C9Z8941rrXfpeAiXyQLYxaJPg5GLiVXUZGPqRx26K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

abc = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/abc.ts"

zero-copy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/zero-copy.ts"
