[toolchain]
solana_version = "1.17.5"

[features]
seeds = false
skip-lint = false

[programs.localnet]
abc = "7mMu435prH2sgPhnT2UuYTCCMfQyxdA8XpwLX7sEx6L7"
puppet = "6V7YXxKMPsL1NeJFs5PgkkmTwi5Z5eHfxydi4UxDcBei"
zero_cpi = "3KkGvkE9vY5FkccNkfFhqi9iyoo7QyAVkQ2n6TmmMW3Y"
zero_copy = "Fuuu2RxD8aYzLgTVtMqKhvEnBeWzJYs9s2RPYmytCbok"
token_contract = "AJFx3LkR7oyUE6uWXMTRa5QnR4TXqKkFskJkDzxh5gF5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test1 = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

abc = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/abc.ts"

zero_copy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/zero-copy.ts"

test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/token-contract.ts"
token_contract = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/token-contract.ts"
