[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
abc = "7mMu435prH2sgPhnT2UuYTCCMfQyxdA8XpwLX7sEx6L7"
puppet = "6V7YXxKMPsL1NeJFs5PgkkmTwi5Z5eHfxydi4UxDcBei"
zero_cpi = "3KkGvkE9vY5FkccNkfFhqi9iyoo7QyAVkQ2n6TmmMW3Y"
zero_copy = "Fuuu2RxD8aYzLgTVtMqKhvEnBeWzJYs9s2RPYmytCbok"
token_contract = "4bVCPUmNeVpLaCsSy5d5h2dbD3j25UatrgYzKQL12qpm"
solang = "6fiZW8e4d8XYo4XH2tLoFhxjYWpCfeF32XcAMa2KAZyN"
social_media = "2g5nWKEytXSfgznWR1UsJ1YMHBVK4ztKCxkGecg7CMXo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
#cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test1 = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/token-contract.ts"

test2 = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/abc.ts"

test3 = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/zero-copy.ts"

test4 = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/social-media.ts"

test5 = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/social-media.ts"

test6 = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/solang.ts"

testall = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
