[package]
name = "puppet"
version = "0.1.0"
description = ""
rust-version = "1.68"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "puppet"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-lang = "0.29.0"
